// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package knapcode

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type PrepareAppForWebSignIn struct {
	pulumi.CustomResourceState
}

// NewPrepareAppForWebSignIn registers a new resource with the given unique name, arguments, and options.
func NewPrepareAppForWebSignIn(ctx *pulumi.Context,
	name string, args *PrepareAppForWebSignInArgs, opts ...pulumi.ResourceOption) (*PrepareAppForWebSignIn, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.HostName == nil {
		return nil, errors.New("invalid value for required argument 'HostName'")
	}
	if args.ObjectId == nil {
		return nil, errors.New("invalid value for required argument 'ObjectId'")
	}
	var resource PrepareAppForWebSignIn
	err := ctx.RegisterResource("knapcode:index:PrepareAppForWebSignIn", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetPrepareAppForWebSignIn gets an existing PrepareAppForWebSignIn resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPrepareAppForWebSignIn(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *PrepareAppForWebSignInState, opts ...pulumi.ResourceOption) (*PrepareAppForWebSignIn, error) {
	var resource PrepareAppForWebSignIn
	err := ctx.ReadResource("knapcode:index:PrepareAppForWebSignIn", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering PrepareAppForWebSignIn resources.
type prepareAppForWebSignInState struct {
}

type PrepareAppForWebSignInState struct {
}

func (PrepareAppForWebSignInState) ElementType() reflect.Type {
	return reflect.TypeOf((*prepareAppForWebSignInState)(nil)).Elem()
}

type prepareAppForWebSignInArgs struct {
	HostName string `pulumi:"hostName"`
	ObjectId string `pulumi:"objectId"`
}

// The set of arguments for constructing a PrepareAppForWebSignIn resource.
type PrepareAppForWebSignInArgs struct {
	HostName pulumi.StringInput
	ObjectId pulumi.StringInput
}

func (PrepareAppForWebSignInArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*prepareAppForWebSignInArgs)(nil)).Elem()
}

type PrepareAppForWebSignInInput interface {
	pulumi.Input

	ToPrepareAppForWebSignInOutput() PrepareAppForWebSignInOutput
	ToPrepareAppForWebSignInOutputWithContext(ctx context.Context) PrepareAppForWebSignInOutput
}

func (*PrepareAppForWebSignIn) ElementType() reflect.Type {
	return reflect.TypeOf((*PrepareAppForWebSignIn)(nil))
}

func (i *PrepareAppForWebSignIn) ToPrepareAppForWebSignInOutput() PrepareAppForWebSignInOutput {
	return i.ToPrepareAppForWebSignInOutputWithContext(context.Background())
}

func (i *PrepareAppForWebSignIn) ToPrepareAppForWebSignInOutputWithContext(ctx context.Context) PrepareAppForWebSignInOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PrepareAppForWebSignInOutput)
}

type PrepareAppForWebSignInOutput struct {
	*pulumi.OutputState
}

func (PrepareAppForWebSignInOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*PrepareAppForWebSignIn)(nil))
}

func (o PrepareAppForWebSignInOutput) ToPrepareAppForWebSignInOutput() PrepareAppForWebSignInOutput {
	return o
}

func (o PrepareAppForWebSignInOutput) ToPrepareAppForWebSignInOutputWithContext(ctx context.Context) PrepareAppForWebSignInOutput {
	return o
}

func init() {
	pulumi.RegisterOutputType(PrepareAppForWebSignInOutput{})
}
